[server]
maxUploadSize = 100
headless = true

[theme]
primaryColor = "#b06e11"
backgroundColor = "#fffdf4"
secondaryBackgroundColor = "#fff5dc"
textColor = "#4b2e0f"
font = "serif"

[browser]
gatherUsageStats = false
